services:
  postgres:
    image: postgres:latest
    container_name: otv
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=otv
    restart: always